// examples/vue/ReaderComponent.vue
<script setup>
import { ref, onMounted, onUnmounted, computed } from "vue";
import D2Reader from "../../src";

// ── Configuration ────────────────────────────────────────────────────

const MANIFEST_URL = "https://alice.dita.digital/manifest.json";

const props = defineProps({
  injectables: { type: Array, required: true },
});

const rights = {
  enableBookmarks: true,
  enableAnnotations: true,
  enableSearch: true,
  enableContentProtection: false,
  enableTTS: false,
  enableTimeline: false,
  enableDefinitions: false,
  enableMediaOverlays: false,
  enablePageBreaks: false,
  enableLineFocus: false,
  autoGeneratePositions: true,
};

// ── State ────────────────────────────────────────────────────────────

const reader = ref(null);
const sidebarOpen = ref(false);
const activeTab = ref("toc");
const tick = ref(0);

const pageInfo = ref({});

// Settings panel values (reactive mirrors)
const fontSize = ref(100);
const fontFamily = ref("Original");
const lineHeight = ref(1.5);
const pageMargins = ref(2);
const wordSpacing = ref(0);
const letterSpacing = ref(0);
const paraSpacing = ref(0);
const paraIndent = ref(1);
const textAlignment = ref("auto");
const columnCount = ref("auto");

// Search
const searchTerm = ref("");
const searchResults = ref([]);
const searched = ref(false);

// ── Helpers ──────────────────────────────────────────────────────────

function refresh() {
  tick.value++;
  syncSettings();
}

function syncSettings() {
  if (!reader.value) return;
  const s = reader.value.currentSettings;
  fontSize.value = s.fontSize ?? 100;
  fontFamily.value = s.fontFamily ?? "Original";
  lineHeight.value = s.lineHeight ?? 1.5;
  pageMargins.value = s.pageMargins ?? 2;
  wordSpacing.value = s.wordSpacing ?? 0;
  letterSpacing.value = s.letterSpacing ?? 0;
  paraSpacing.value = s.paraSpacing ?? 0;
  paraIndent.value = s.paraIndent ?? 1;
  textAlignment.value = s.textAlignment ?? "auto";
  columnCount.value = s.columnCount ?? "auto";
}

function updatePageInfo() {
  if (!reader.value) return;
  try {
    const loc = reader.value.currentLocator;
    if (loc) {
      pageInfo.value = {
        chapterTitle: loc.title,
        pageIndex: loc.displayInfo?.resourceScreenIndex,
        pageCount: loc.displayInfo?.resourceScreenCount,
        progression: loc.locations?.progression,
        totalProgression: loc.locations?.totalProgression,
      };
    }
    const a = reader.value.currentSettings?.appearance;
    if (a) appearance.value = a;
  } catch (_) {
    /* locator may not be ready */
  }
}

// ── Theme ───────────────────────────────────────────────────────────

const appearance = ref("day");
const themeMap = {
  day: { bg: "#FFFFFF", fg: "#121212", border: "#e0e0e0" },
  sepia: { bg: "#faf4e8", fg: "#121212", border: "#e0d0b0" },
  night: { bg: "#000000", fg: "#FEFEFE", border: "#333333" },
  "readium-default-on": { bg: "#FFFFFF", fg: "#121212", border: "#e0e0e0" },
  "readium-sepia-on": { bg: "#faf4e8", fg: "#121212", border: "#e0d0b0" },
  "readium-night-on": { bg: "#000000", fg: "#FEFEFE", border: "#333333" },
};
const theme = computed(() => themeMap[appearance.value] || themeMap.day);

// ── Computed ─────────────────────────────────────────────────────────

const isScrolling = computed(() => { tick.value; return reader.value?.currentSettings?.verticalScroll ?? false; });

const toc = computed(() => { tick.value; return reader.value?.tableOfContents || []; });

const bookmarks = computed(() => {
  // tick dependency for reactivity on bookmark changes
  void tick.value;
  return reader.value?.bookmarks || [];
});

// ── Reader actions ───────────────────────────────────────────────────

function prevPage() {
  reader.value?.previousPage();
  setTimeout(updatePageInfo, 150);
}

function nextPage() {
  reader.value?.nextPage();
  setTimeout(updatePageInfo, 150);
}

function setScroll(scroll) {
  reader.value?.scroll(scroll);
  refresh();
}

function saveBookmark() {
  reader.value?.saveBookmark();
  refresh();
}

function deleteBookmark(bm) {
  reader.value?.deleteBookmark(bm);
  refresh();
}

function goTo(locator) {
  reader.value?.goTo(locator);
  sidebarOpen.value = false;
  setTimeout(updatePageInfo, 150);
}

function goToTocItem(item) {
  reader.value?.goTo({ href: item.href, locations: {}, title: item.title });
  sidebarOpen.value = false;
  setTimeout(updatePageInfo, 150);
}

function applySetting(settings) {
  reader.value?.applyUserSettings(settings);
  refresh();
}

function resetSettings() {
  reader.value?.resetUserSettings();
  refresh();
}

function setAppearance(mode) {
  applySetting({ appearance: mode });
}

// ── Search ───────────────────────────────────────────────────────────

async function doSearch() {
  if (!searchTerm.value.trim() || !reader.value) return;
  const res = await reader.value.search(searchTerm.value.trim(), false);
  searchResults.value = res || [];
  searched.value = true;
}

async function clearSearch() {
  if (reader.value) await reader.value.clearSearch();
  searchResults.value = [];
  searched.value = false;
  searchTerm.value = "";
}

function goToSearchResult(r) {
  reader.value?.goToSearchID(r.href, r.uuid, false);
  sidebarOpen.value = false;
}

// ── Keyboard ─────────────────────────────────────────────────────────

function onKeydown(e) {
  if (!reader.value) return;
  if (e.key === "ArrowRight") {
    reader.value.nextPage();
    setTimeout(updatePageInfo, 100);
  }
  if (e.key === "ArrowLeft") {
    reader.value.previousPage();
    setTimeout(updatePageInfo, 100);
  }
}

// ── Lifecycle ────────────────────────────────────────────────────────

onMounted(async () => {
  const r = await D2Reader.load({
    url: new URL(MANIFEST_URL),
    injectables: props.injectables,
    injectablesFixed: [],
    rights,
    api: {
      updateCurrentLocation: async () => {},
      updateSettings: async (settings) => {
        if (settings?.appearance) appearance.value = settings.appearance;
      },
    },
  });

  reader.value = r;
  syncSettings();

  r.addEventListener("resource.ready", () => updatePageInfo());
  r.addEventListener("click", () => setTimeout(updatePageInfo, 100));
  setTimeout(updatePageInfo, 500);

  window.addEventListener("keydown", onKeydown);
});

onUnmounted(() => {
  window.removeEventListener("keydown", onKeydown);
  reader.value?.stop();
});
</script>

<template>
  <!-- Toolbar -->
  <div v-if="reader" class="toolbar" :style="{ background: theme.bg, color: theme.fg, borderColor: theme.border }">
    <button class="btn" @click="sidebarOpen = !sidebarOpen">
      {{ sidebarOpen ? "\u2715" : "\u2630" }}
    </button>

    <span class="badge">Vue</span>
    <div class="sep" />

    <button class="btn" @click="prevPage">&larr;</button>
    <button class="btn" @click="nextPage">&rarr;</button>

    <div class="sep" />

    <button class="btn" :class="{ active: isScrolling }" @click="setScroll(true)">
      Scroll
    </button>
    <button class="btn" :class="{ active: !isScrolling }" @click="setScroll(false)">
      Pages
    </button>

    <div class="sep" />

    <span class="page-info">
      <span v-if="pageInfo.chapterTitle" class="chapter-title">
        {{ pageInfo.chapterTitle }}
      </span>
      <span v-if="pageInfo.pageIndex != null && pageInfo.pageCount != null && !isScrolling">
        Page {{ pageInfo.pageIndex }} of {{ pageInfo.pageCount }}
      </span>
      <span v-if="pageInfo.totalProgression != null" class="progression">
        {{ Math.round(pageInfo.totalProgression * 100) }}%
      </span>
    </span>

    <div class="spacer" />

    <button class="btn" @click="saveBookmark">Bookmark</button>
  </div>

  <!-- Sidebar overlay -->
  <div v-if="sidebarOpen" class="overlay" @click="sidebarOpen = false" />

  <!-- Sidebar -->
  <div v-if="reader" class="sidebar" :class="{ hidden: !sidebarOpen }" :style="{ background: theme.bg, color: theme.fg, borderColor: theme.border }">
    <!-- Tab bar -->
    <div class="tab-bar">
      <button
        v-for="tab in ['toc', 'settings', 'bookmarks', 'search']"
        :key="tab"
        class="tab-btn"
        :class="{ active: activeTab === tab }"
        @click="activeTab = tab"
      >
        {{ tab }}
      </button>
    </div>

    <!-- TOC panel -->
    <div v-if="activeTab === 'toc'">
      <div v-if="toc.length === 0" class="empty">No table of contents</div>
      <div
        v-for="(item, i) in toc"
        :key="i"
        class="toc-item"
        @click="goToTocItem(item)"
      >
        {{ item.title || item.href }}
      </div>
    </div>

    <!-- Settings panel -->
    <div v-if="activeTab === 'settings'" class="settings-panel">
      <div class="setting-row">
        <span class="label">Font Size</span>
        <input
          type="range"
          class="slider"
          :min="100"
          :max="300"
          :step="25"
          :value="fontSize"
          @input="applySetting({ fontSize: Number($event.target.value) })"
        />
        <span class="value">{{ fontSize }}%</span>
      </div>

      <div class="setting-row">
        <span class="label">Font</span>
        <select
          class="select"
          :value="fontFamily"
          @change="applySetting({ fontFamily: $event.target.value })"
        >
          <option value="Original">Publisher</option>
          <option value="serif">Serif</option>
          <option value="sans-serif">Sans-serif</option>
          <option value="opendyslexic">Open Dyslexic</option>
        </select>
      </div>

      <div class="setting-row">
        <span class="label">Theme</span>
        <div class="btn-group">
          <button
            v-for="(mode, i) in ['day', 'sepia', 'night']"
            :key="mode"
            class="btn theme-btn"
            :class="[
              mode,
              { first: i === 0, last: i === 2 },
            ]"
            @click="setAppearance(mode)"
          >
            {{ mode }}
          </button>
        </div>
      </div>

      <div class="setting-row">
        <span class="label">Layout</span>
        <div class="btn-group">
          <button
            class="btn first"
            :class="{ active: isScrolling }"
            @click="setScroll(true)"
          >
            Scroll
          </button>
          <button
            class="btn last"
            :class="{ active: !isScrolling }"
            @click="setScroll(false)"
          >
            Pages
          </button>
        </div>
      </div>

      <div class="setting-row">
        <span class="label">Line Height</span>
        <input
          type="range"
          class="slider"
          :min="1"
          :max="2"
          :step="0.25"
          :value="lineHeight"
          @input="applySetting({ lineHeight: Number($event.target.value) })"
        />
      </div>

      <div class="setting-row">
        <span class="label">Margins</span>
        <input
          type="range"
          class="slider"
          :min="0.5"
          :max="4"
          :step="0.25"
          :value="pageMargins"
          @input="applySetting({ pageMargins: Number($event.target.value) })"
        />
      </div>

      <div class="setting-row">
        <span class="label">Word Spacing</span>
        <input
          type="range"
          class="slider"
          :min="0"
          :max="1"
          :step="0.25"
          :value="wordSpacing"
          @input="applySetting({ wordSpacing: Number($event.target.value) })"
        />
      </div>

      <div class="setting-row">
        <span class="label">Letter Spacing</span>
        <input
          type="range"
          class="slider"
          :min="0"
          :max="0.5"
          :step="0.0625"
          :value="letterSpacing"
          @input="applySetting({ letterSpacing: Number($event.target.value) })"
        />
      </div>

      <div class="setting-row">
        <span class="label">Paragraph Spacing</span>
        <input
          type="range"
          class="slider"
          :min="0"
          :max="3"
          :step="0.5"
          :value="paraSpacing"
          @input="applySetting({ paraSpacing: Number($event.target.value) })"
        />
      </div>

      <div class="setting-row">
        <span class="label">Paragraph Indent</span>
        <input
          type="range"
          class="slider"
          :min="0"
          :max="3"
          :step="0.5"
          :value="paraIndent"
          @input="applySetting({ paraIndent: Number($event.target.value) })"
        />
      </div>

      <div class="setting-row">
        <span class="label">Align</span>
        <select
          class="select"
          :value="textAlignment"
          @change="applySetting({ textAlignment: $event.target.value })"
        >
          <option value="auto">Auto</option>
          <option value="justify">Justify</option>
          <option value="start">Start</option>
        </select>
      </div>

      <div class="setting-row">
        <span class="label">Columns</span>
        <select
          class="select"
          :value="columnCount"
          @change="applySetting({ columnCount: $event.target.value })"
        >
          <option value="auto">Auto</option>
          <option value="1">Single</option>
          <option value="2">Double</option>
        </select>
      </div>

      <button class="btn reset-btn" @click="resetSettings">Reset</button>
    </div>

    <!-- Bookmarks panel -->
    <div v-if="activeTab === 'bookmarks'">
      <div class="bookmark-add">
        <button class="btn full-width" @click="saveBookmark">+ Add Bookmark</button>
      </div>
      <div v-if="bookmarks.length === 0" class="empty">No bookmarks yet</div>
      <div
        v-for="(bm, i) in bookmarks"
        :key="bm.id || i"
        class="bookmark-item"
      >
        <span class="bookmark-label" @click="goTo(bm)">
          {{ bm.href?.split('/').pop() || bm.href }}
          <span v-if="bm.locations?.progression != null" class="progression">
            ({{ Math.round(bm.locations.progression * 100) }}%)
          </span>
        </span>
        <button class="delete-btn" @click="deleteBookmark(bm)">&times;</button>
      </div>
    </div>

    <!-- Search panel -->
    <div v-if="activeTab === 'search'">
      <div class="search-bar">
        <input
          v-model="searchTerm"
          type="text"
          class="search-input"
          placeholder="Search..."
          @keydown.enter="doSearch"
        />
        <button class="btn" @click="doSearch">Go</button>
        <button v-if="searched" class="btn" @click="clearSearch">&times;</button>
      </div>
      <div v-if="searched && searchResults.length === 0" class="empty">No results found</div>
      <div
        v-for="(r, i) in searchResults"
        :key="r.uuid ?? i"
        class="toc-item search-result"
        @click="goToSearchResult(r)"
      >
        <span class="muted">&hellip;{{ r.textBefore }}</span>
        <mark>{{ r.textMatch }}</mark>
        <span class="muted">{{ r.textAfter }}&hellip;</span>
      </div>
    </div>
  </div>

  <!-- Loading screen (before reader is ready) -->
  <div v-if="!reader" class="loading-screen">Loading reader&hellip;</div>

  <!-- Reader container (required DOM structure) -->
  <div id="D2Reader-Container" :style="{ paddingTop: reader ? '42px' : '0', background: theme.bg }">
    <main
      id="iframe-wrapper"
      tabindex="-1"
      :style="{ height: reader ? 'calc(100vh - 42px)' : '100vh' }"
    >
      <div id="reader-loading" class="loading" />
      <div id="reader-error" class="error" />
    </main>
  </div>
</template>

<style scoped>
/* ── Badge ──────────────────────────────────────────────────── */
.badge {
  font-size: 9px; font-weight: 700; text-transform: uppercase; letter-spacing: 1px;
  padding: 2px 8px; border-radius: 10px; color: #fff; background: #42b883; flex-shrink: 0;
}

/* ── Layout ─────────────────────────────────────────────────── */

.toolbar {
  position: fixed;
  top: 0;
  left: 0;
  right: 0;
  z-index: 10;
  display: flex;
  align-items: center;
  gap: 6px;
  padding: 0 10px;
  height: 42px;
  background: rgba(255, 255, 255, 0.97);
  backdrop-filter: blur(8px);
  border-bottom: 1px solid #e0e0e0;
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
  font-size: 12px;
}

.spacer {
  flex: 1;
}

.sep {
  width: 1px;
  height: 18px;
  background: rgba(128,128,128,0.2);
  flex-shrink: 0;
}

/* ── Buttons ────────────────────────────────────────────────── */

.btn {
  padding: 4px 10px;
  font-size: 11px;
  border: 1px solid #d0d0d0;
  border-radius: 14px;
  background: transparent;
  cursor: pointer;
  color: inherit;
  text-transform: uppercase;
  letter-spacing: 0.4px;
  white-space: nowrap;
}

.btn:hover {
  background: rgba(128,128,128,0.1);
}

.btn.active {
  background: rgba(128,128,128,0.2);
  font-weight: 600;
}

.btn-group {
  display: flex;
  gap: 0;
}

.btn-group .btn {
  border-radius: 0;
  min-width: 60px;
}

.btn.first {
  border-radius: 14px 0 0 14px;
}

.btn.last {
  border-radius: 0 14px 14px 0;
}

.theme-btn.day {
  background: transparent;
  color: inherit;
}

.theme-btn.sepia {
  background: #f5e6c8;
  color: inherit;
}

.theme-btn.night {
  background: #121212;
  color: #fff;
}

.full-width {
  width: 100%;
}

.reset-btn {
  margin-top: 8px;
  align-self: center;
}

.delete-btn {
  font-size: 10px;
  color: #c00;
  cursor: pointer;
  border: none;
  background: none;
  padding: 2px 6px;
}

/* ── Page info ──────────────────────────────────────────────── */

.page-info {
  font-size: 11px;
  color: inherit; opacity: 0.7;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}

.chapter-title {
  color: inherit; opacity: 0.5;
  margin-right: 6px;
}

.progression {
  color: inherit; opacity: 0.5;
  margin-left: 6px;
}

/* ── Sidebar ────────────────────────────────────────────────── */

.sidebar {
  position: fixed;
  top: 42px;
  bottom: 0;
  left: 0;
  width: 280px;
  background: inherit;
  border-right: 1px solid #e0e0e0;
  overflow-y: auto;
  padding: 0;
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
  font-size: 12px;
  z-index: 9;
  transition: transform 0.2s ease;
}

.sidebar.hidden {
  transform: translateX(-280px);
}

.overlay {
  position: fixed;
  inset: 0;
  background: rgba(0, 0, 0, 0.15);
  z-index: 8;
}

/* ── Tab bar ────────────────────────────────────────────────── */

.tab-bar {
  display: flex;
  border-bottom: 1px solid #e0e0e0;
}

.tab-btn {
  flex: 1;
  padding: 8px 0;
  font-size: 10px;
  text-transform: uppercase;
  letter-spacing: 0.5px;
  border: none;
  cursor: pointer;
  background: transparent;
  font-weight: 400;
  color: inherit;
}

.tab-btn.active {
  background: rgba(128,128,128,0.15);
  font-weight: 600;
}

/* ── TOC ────────────────────────────────────────────────────── */

.toc-item {
  padding: 6px 14px;
  cursor: pointer;
  color: inherit;
  border-bottom: 1px solid #f0f0f0;
  line-height: 1.4;
}

.toc-item:hover {
  background: rgba(128,128,128,0.15);
}

.search-result {
  font-size: 11px;
}

.muted {
  color: inherit; opacity: 0.5;
}

.empty {
  padding: 14px;
  color: inherit; opacity: 0.5;
}

/* ── Settings ───────────────────────────────────────────────── */

.settings-panel {
  padding: 8px 12px;
  display: flex;
  flex-direction: column;
  gap: 8px;
}

.setting-row {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 6px;
}

.label {
  font-size: 11px;
  color: inherit; opacity: 0.7;
  flex-shrink: 0;
}

.value {
  font-size: 10px;
  color: inherit; opacity: 0.5;
  min-width: 28px;
  text-align: right;
}

.slider {
  width: 70px;
  accent-color: #4a90d9;
}

.select {
  padding: 4px 6px;
  font-size: 11px;
  border: 1px solid #d0d0d0;
  border-radius: 6px;
  background: transparent;
  color: inherit;
}

/* ── Bookmarks ──────────────────────────────────────────────── */

.bookmark-add {
  padding: 8px 14px;
  border-bottom: 1px solid #e0e0e0;
}

.bookmark-item {
  padding: 8px 14px;
  cursor: pointer;
  color: inherit;
  border-bottom: 1px solid #f0f0f0;
  font-size: 11px;
  line-height: 1.4;
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.bookmark-label {
  cursor: pointer;
  flex: 1;
}

/* ── Search ─────────────────────────────────────────────────── */

.search-bar {
  padding: 8px 12px;
  display: flex;
  gap: 6px;
}

.search-input {
  flex: 1;
  padding: 6px 8px;
  font-size: 11px;
  border: 1px solid #d0d0d0;
  border-radius: 6px;
  outline: none;
}

.search-input:focus {
  border-color: #4a90d9;
}

/* ── Loading ────────────────────────────────────────────────── */

.loading-screen {
  display: flex;
  align-items: center;
  justify-content: center;
  height: 100vh;
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
  color: inherit; opacity: 0.5;
  font-size: 16px;
}
</style>

// examples/angular/reader.component.ts
import {
  Component,
  OnInit,
  OnDestroy,
  ChangeDetectorRef,
  ChangeDetectionStrategy,
} from "@angular/core";
import { CommonModule } from "@angular/common";
import D2Reader from "@d-i-t-a/reader";

interface TocItem {
  title: string;
  href: string;
  children?: TocItem[];
}

@Component({
  selector: "app-reader",
  standalone: true,
  imports: [CommonModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <!-- Toolbar -->
    <div class="toolbar" *ngIf="reader">
      <div class="toolbar-group">
        <button class="btn" (click)="toggleToc()" title="Table of Contents">
          <svg
            width="20"
            height="20"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            stroke-width="2"
          >
            <line x1="3" y1="6" x2="21" y2="6" />
            <line x1="3" y1="12" x2="21" y2="12" />
            <line x1="3" y1="18" x2="21" y2="18" />
          </svg>
        </button>
        <button
          class="btn"
          (click)="previousPage()"
          [disabled]="isAtStart"
          title="Previous Page"
        >
          <svg
            width="20"
            height="20"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            stroke-width="2"
          >
            <polyline points="15 18 9 12 15 6" />
          </svg>
        </button>
        <button
          class="btn"
          (click)="nextPage()"
          [disabled]="isAtEnd"
          title="Next Page"
        >
          <svg
            width="20"
            height="20"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            stroke-width="2"
          >
            <polyline points="9 18 15 12 9 6" />
          </svg>
        </button>
      </div>

      <div class="toolbar-info">
        <span class="chapter-title">{{ chapterTitle }}</span>
        <span class="page-info" *ngIf="currentPage > 0">
          Page {{ currentPage }} of {{ totalPages }}
          <span class="progress-text">({{ progressPercent }}%)</span>
        </span>
      </div>

      <div class="toolbar-group">
        <button
          class="btn"
          (click)="toggleScrollMode()"
          [title]="isScrolling ? 'Switch to paginated' : 'Switch to scroll'"
        >
          <svg
            width="20"
            height="20"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            stroke-width="2"
          >
            <rect
              *ngIf="!isScrolling"
              x="3"
              y="3"
              width="18"
              height="18"
              rx="2"
            />
            <line *ngIf="isScrolling" x1="12" y1="3" x2="12" y2="21" />
            <polyline *ngIf="isScrolling" points="8 7 12 3 16 7" />
            <polyline *ngIf="isScrolling" points="8 17 12 21 16 17" />
          </svg>
        </button>
        <button class="btn" (click)="saveBookmark()" title="Bookmark this page">
          <svg
            width="20"
            height="20"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            stroke-width="2"
          >
            <path d="M19 21l-7-5-7 5V5a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2z" />
          </svg>
        </button>
        <button class="btn" (click)="toggleSettings()" title="Settings">
          <svg
            width="20"
            height="20"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            stroke-width="2"
          >
            <circle cx="12" cy="12" r="3" />
            <path
              d="M19.4 15a1.65 1.65 0 0 0 .33 1.82l.06.06a2 2 0 1 1-2.83 2.83l-.06-.06a1.65 1.65 0 0 0-1.82-.33 1.65 1.65 0 0 0-1 1.51V21a2 2 0 0 1-4 0v-.09A1.65 1.65 0 0 0 9 19.4a1.65 1.65 0 0 0-1.82.33l-.06.06a2 2 0 1 1-2.83-2.83l.06-.06A1.65 1.65 0 0 0 4.68 15a1.65 1.65 0 0 0-1.51-1H3a2 2 0 0 1 0-4h.09A1.65 1.65 0 0 0 4.6 9a1.65 1.65 0 0 0-.33-1.82l-.06-.06a2 2 0 1 1 2.83-2.83l.06.06A1.65 1.65 0 0 0 9 4.68a1.65 1.65 0 0 0 1-1.51V3a2 2 0 0 1 4 0v.09a1.65 1.65 0 0 0 1 1.51 1.65 1.65 0 0 0 1.82-.33l.06-.06a2 2 0 1 1 2.83 2.83l-.06.06A1.65 1.65 0 0 0 19.4 9a1.65 1.65 0 0 0 1.51 1H21a2 2 0 0 1 0 4h-.09a1.65 1.65 0 0 0-1.51 1z"
            />
          </svg>
        </button>
      </div>
    </div>

    <!-- Progress bar -->
    <div class="progress-bar" *ngIf="reader">
      <div class="progress-fill" [style.width.%]="progressPercent"></div>
    </div>

    <!-- TOC Sidebar -->
    <div class="toc-overlay" *ngIf="tocOpen" (click)="toggleToc()"></div>
    <div class="toc-sidebar" [class.open]="tocOpen">
      <div class="toc-header">
        <h3>Table of Contents</h3>
        <button class="btn btn-close" (click)="toggleToc()">
          <svg
            width="20"
            height="20"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            stroke-width="2"
          >
            <line x1="18" y1="6" x2="6" y2="18" />
            <line x1="6" y1="6" x2="18" y2="18" />
          </svg>
        </button>
      </div>
      <ul class="toc-list">
        <ng-container *ngFor="let item of toc">
          <ng-container
            *ngTemplateOutlet="
              tocItemTpl;
              context: { $implicit: item, depth: 0 }
            "
          ></ng-container>
        </ng-container>
      </ul>

      <ng-template #tocItemTpl let-item let-depth="depth">
        <li class="toc-item" [style.padding-left.px]="16 + depth * 16">
          <a (click)="goToTocItem(item)">{{ item.title }}</a>
        </li>
        <ng-container *ngIf="item.children?.length">
          <ng-container *ngFor="let child of item.children">
            <ng-container
              *ngTemplateOutlet="
                tocItemTpl;
                context: { $implicit: child, depth: depth + 1 }
              "
            ></ng-container>
          </ng-container>
        </ng-container>
      </ng-template>
    </div>

    <!-- Settings Panel -->
    <div
      class="settings-overlay"
      *ngIf="settingsOpen"
      (click)="toggleSettings()"
    ></div>
    <div class="settings-panel" [class.open]="settingsOpen">
      <div class="settings-header">
        <h3>Settings</h3>
        <button class="btn btn-close" (click)="toggleSettings()">
          <svg
            width="20"
            height="20"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            stroke-width="2"
          >
            <line x1="18" y1="6" x2="6" y2="18" />
            <line x1="6" y1="6" x2="18" y2="18" />
          </svg>
        </button>
      </div>

      <div class="settings-section">
        <label class="settings-label">Font Size</label>
        <div class="settings-row">
          <button class="btn btn-setting" (click)="decreaseFontSize()">
            A-
          </button>
          <span class="setting-value">{{ fontSizeLabel }}</span>
          <button class="btn btn-setting" (click)="increaseFontSize()">
            A+
          </button>
        </div>
      </div>

      <div class="settings-section">
        <label class="settings-label">Appearance</label>
        <div class="settings-row appearance-row">
          <button
            class="btn btn-appearance"
            [class.active]="appearance === 'readium-default-on'"
            (click)="setAppearance('readium-default-on')"
          >
            <span class="appearance-preview light-preview">Aa</span>
            <span>Light</span>
          </button>
          <button
            class="btn btn-appearance"
            [class.active]="appearance === 'readium-sepia-on'"
            (click)="setAppearance('readium-sepia-on')"
          >
            <span class="appearance-preview sepia-preview">Aa</span>
            <span>Sepia</span>
          </button>
          <button
            class="btn btn-appearance"
            [class.active]="appearance === 'readium-night-on'"
            (click)="setAppearance('readium-night-on')"
          >
            <span class="appearance-preview dark-preview">Aa</span>
            <span>Dark</span>
          </button>
        </div>
      </div>

      <div class="settings-section">
        <button class="btn btn-reset" (click)="resetSettings()">
          Reset to Defaults
        </button>
      </div>
    </div>

    <!-- Reader Container (required DOM structure) -->
    <div id="D2Reader-Container">
      <main id="iframe-wrapper" tabindex="-1">
        <div id="reader-loading" class="loading" *ngIf="!reader">
          <div class="spinner"></div>
          <p>Loading reader...</p>
        </div>
        <div id="reader-error" class="error"></div>
      </main>
    </div>
  `,
  styles: [
    `
      :host {
        display: block;
        font-family:
          -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica,
          Arial, sans-serif;
        height: 100vh;
        overflow: hidden;
        position: relative;
      }

      /* Toolbar */
      .toolbar {
        position: fixed;
        top: 0;
        left: 0;
        right: 0;
        z-index: 100;
        height: 48px;
        background: #ffffff;
        border-bottom: 1px solid #e0e0e0;
        display: flex;
        align-items: center;
        justify-content: space-between;
        padding: 0 12px;
        box-shadow: 0 1px 3px rgba(0, 0, 0, 0.08);
      }

      .toolbar-group {
        display: flex;
        align-items: center;
        gap: 4px;
      }

      .toolbar-info {
        display: flex;
        flex-direction: column;
        align-items: center;
        min-width: 0;
      }

      .chapter-title {
        font-size: 13px;
        font-weight: 600;
        color: #333;
        white-space: nowrap;
        overflow: hidden;
        text-overflow: ellipsis;
        max-width: 300px;
      }

      .page-info {
        font-size: 11px;
        color: #888;
      }

      .progress-text {
        color: #aaa;
      }

      /* Buttons */
      .btn {
        background: none;
        border: 1px solid transparent;
        border-radius: 6px;
        padding: 6px 8px;
        cursor: pointer;
        color: #555;
        display: inline-flex;
        align-items: center;
        justify-content: center;
        transition:
          background 0.15s,
          color 0.15s;
      }

      .btn:hover {
        background: #f0f0f0;
        color: #111;
      }

      .btn:disabled {
        opacity: 0.35;
        cursor: default;
      }

      .btn:disabled:hover {
        background: none;
      }

      .btn-close {
        padding: 4px;
      }

      .btn-setting {
        font-size: 14px;
        font-weight: 600;
        padding: 6px 14px;
        border: 1px solid #ddd;
        border-radius: 6px;
        min-width: 44px;
      }

      .btn-reset {
        width: 100%;
        padding: 10px;
        border: 1px solid #ddd;
        border-radius: 6px;
        font-size: 13px;
        color: #555;
      }

      .btn-reset:hover {
        background: #f5f5f5;
      }

      /* Progress Bar */
      .progress-bar {
        position: fixed;
        top: 48px;
        left: 0;
        right: 0;
        height: 2px;
        background: #eee;
        z-index: 100;
      }

      .progress-fill {
        height: 100%;
        background: #6366f1;
        transition: width 0.3s ease;
      }

      /* TOC Sidebar */
      .toc-overlay,
      .settings-overlay {
        position: fixed;
        inset: 0;
        background: rgba(0, 0, 0, 0.3);
        z-index: 200;
      }

      .toc-sidebar {
        position: fixed;
        top: 0;
        left: -320px;
        width: 320px;
        height: 100vh;
        background: #fff;
        z-index: 300;
        box-shadow: 2px 0 12px rgba(0, 0, 0, 0.15);
        transition: left 0.25s ease;
        display: flex;
        flex-direction: column;
      }

      .toc-sidebar.open {
        left: 0;
      }

      .toc-header,
      .settings-header {
        display: flex;
        align-items: center;
        justify-content: space-between;
        padding: 16px;
        border-bottom: 1px solid #eee;
      }

      .toc-header h3,
      .settings-header h3 {
        margin: 0;
        font-size: 16px;
        font-weight: 600;
        color: #333;
      }

      .toc-list {
        list-style: none;
        margin: 0;
        padding: 8px 0;
        overflow-y: auto;
        flex: 1;
      }

      .toc-item a {
        display: block;
        padding: 10px 16px;
        font-size: 14px;
        color: #444;
        text-decoration: none;
        cursor: pointer;
        border-radius: 4px;
        margin: 0 8px;
        transition: background 0.15s;
      }

      .toc-item a:hover {
        background: #f5f5f5;
        color: #111;
      }

      /* Settings Panel */
      .settings-panel {
        position: fixed;
        top: 0;
        right: -360px;
        width: 360px;
        height: 100vh;
        background: #fff;
        z-index: 300;
        box-shadow: -2px 0 12px rgba(0, 0, 0, 0.15);
        transition: right 0.25s ease;
        display: flex;
        flex-direction: column;
      }

      .settings-panel.open {
        right: 0;
      }

      .settings-section {
        padding: 20px 16px;
        border-bottom: 1px solid #f0f0f0;
      }

      .settings-label {
        display: block;
        font-size: 12px;
        font-weight: 600;
        text-transform: uppercase;
        letter-spacing: 0.5px;
        color: #888;
        margin-bottom: 12px;
      }

      .settings-row {
        display: flex;
        align-items: center;
        justify-content: center;
        gap: 16px;
      }

      .setting-value {
        font-size: 14px;
        font-weight: 500;
        min-width: 36px;
        text-align: center;
        color: #333;
      }

      .appearance-row {
        gap: 12px;
      }

      .btn-appearance {
        flex: 1;
        flex-direction: column;
        gap: 6px;
        padding: 12px 8px;
        border: 2px solid #eee;
        border-radius: 8px;
        font-size: 12px;
        color: #666;
      }

      .btn-appearance.active {
        border-color: #6366f1;
        color: #6366f1;
      }

      .appearance-preview {
        font-size: 20px;
        font-weight: 700;
        display: block;
        width: 48px;
        height: 36px;
        line-height: 36px;
        border-radius: 4px;
        text-align: center;
      }

      .light-preview {
        background: #fff;
        color: #333;
        border: 1px solid #ddd;
      }

      .sepia-preview {
        background: #f5e6c8;
        color: #5b4636;
      }

      .dark-preview {
        background: #1e1e1e;
        color: #e0e0e0;
      }

      /* Reader Container */
      #D2Reader-Container {
        position: absolute;
        top: 50px;
        left: 0;
        right: 0;
        bottom: 0;
      }

      #iframe-wrapper {
        height: 100%;
        outline: none;
      }

      /* Loading State */
      .loading {
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
        height: 100%;
        color: #888;
      }

      .spinner {
        width: 32px;
        height: 32px;
        border: 3px solid #e0e0e0;
        border-top: 3px solid #6366f1;
        border-radius: 50%;
        animation: spin 0.8s linear infinite;
        margin-bottom: 12px;
      }

      @keyframes spin {
        to {
          transform: rotate(360deg);
        }
      }

      .loading p {
        font-size: 14px;
        margin: 0;
      }

      .error {
        color: #dc2626;
        text-align: center;
        padding: 20px;
      }
    `,
  ],
})
export class ReaderComponent implements OnInit, OnDestroy {
  reader: D2Reader | null = null;

  // Page info
  chapterTitle = "";
  currentPage = 0;
  totalPages = 0;
  progressPercent = 0;

  // UI state
  isScrolling = false;
  isAtStart = true;
  isAtEnd = false;
  tocOpen = false;
  settingsOpen = false;

  // Settings
  fontSizeLabel = "100%";
  appearance = "readium-default-on";

  // TOC
  toc: TocItem[] = [];

  constructor(private cdr: ChangeDetectorRef) {}

  async ngOnInit(): Promise<void> {
    try {
      const url = new URL("https://alice.dita.digital/manifest.json");

      this.reader = await D2Reader.load({
        url,
        injectables: [
          {
            type: "style",
            url: "/assets/readium-css/ReadiumCSS-before.css",
            r2before: true,
          },
          {
            type: "style",
            url: "/assets/readium-css/ReadiumCSS-default.css",
            r2default: true,
          },
          {
            type: "style",
            url: "/assets/readium-css/ReadiumCSS-after.css",
            r2after: true,
          },
        ],
        injectablesFixed: [],
        rights: {
          enableBookmarks: true,
          enableAnnotations: true,
          enableSearch: true,
          autoGeneratePositions: true,
        },
      });

      this.toc = this.reader.tableOfContents;
      this.updatePageInfo();

      this.reader.addEventListener("resource.ready", () => {
        this.updatePageInfo();
        this.cdr.detectChanges();
      });
    } catch (err) {
      console.error("Failed to load D2Reader:", err);
    }
  }

  ngOnDestroy(): void {
    if (this.reader) {
      this.reader.stop();
      this.reader = null;
    }
  }

  // --- Navigation ---

  async previousPage(): Promise<void> {
    await this.reader?.previousPage();
    this.updatePageInfo();
  }

  async nextPage(): Promise<void> {
    await this.reader?.nextPage();
    this.updatePageInfo();
  }

  // --- Scroll / Paginate ---

  async toggleScrollMode(): Promise<void> {
    if (!this.reader) return;
    const next = !this.isScrolling;
    await this.reader.scroll(next);
    this.isScrolling = next;
    this.cdr.detectChanges();
  }

  // --- Bookmark ---

  async saveBookmark(): Promise<void> {
    if (!this.reader) return;
    const saved = await this.reader.saveBookmark();
    if (saved) {
      console.log("Bookmark saved");
    }
  }

  // --- TOC ---

  toggleToc(): void {
    this.tocOpen = !this.tocOpen;
    if (this.tocOpen) {
      this.settingsOpen = false;
    }
  }

  async goToTocItem(item: TocItem): Promise<void> {
    if (!this.reader) return;
    await this.reader.goTo({ href: item.href } as any);
    this.tocOpen = false;
    this.updatePageInfo();
  }

  // --- Settings ---

  toggleSettings(): void {
    this.settingsOpen = !this.settingsOpen;
    if (this.settingsOpen) {
      this.tocOpen = false;
    }
  }

  async increaseFontSize(): Promise<void> {
    await this.reader?.increase("fontSize");
    this.updateFontSizeLabel();
  }

  async decreaseFontSize(): Promise<void> {
    await this.reader?.decrease("fontSize");
    this.updateFontSizeLabel();
  }

  async setAppearance(value: string): Promise<void> {
    if (!this.reader) return;
    await this.reader.applyUserSettings({ appearance: value } as any);
    this.appearance = value;
    this.cdr.detectChanges();
  }

  async resetSettings(): Promise<void> {
    await this.reader?.resetUserSettings();
    this.appearance = "readium-default-on";
    this.updateFontSizeLabel();
    this.cdr.detectChanges();
  }

  // --- Helpers ---

  private updatePageInfo(): void {
    if (!this.reader) return;

    const locator = this.reader.currentLocator;
    if (locator) {
      this.chapterTitle = locator.title ?? "";
      const position = locator.locations?.position ?? 0;
      const progression = locator.locations?.totalProgression ?? 0;
      this.currentPage = position;
      this.progressPercent = Math.round(progression * 100);
    }

    const positions = this.reader.positions;
    this.totalPages = positions?.length ?? 0;

    this.isScrolling = this.reader.currentSettings?.verticalScroll ?? false;
    this.isAtStart = this.reader.atStart;
    this.isAtEnd = this.reader.atEnd;

    this.updateFontSizeLabel();
    this.cdr.detectChanges();
  }

  private updateFontSizeLabel(): void {
    const fontSize = this.reader?.currentSettings?.fontSize;
    this.fontSizeLabel = fontSize != null ? `${fontSize}%` : "100%";
  }
}
